version: '2.1'
jobs:
  build:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform Validate
          command: terraform validate
      - run:
          name: Terraform Plan
          command: terraform plan
      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve
      - run:
          name: Terraform Output
          command: terraform output -json > output.json
      - store_artifacts:
          path: output.json
          destination: output
      - run:
          name: Cleanup
          command: terraform destroy -auto-approve

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build